### ISSUE TITLE
Create simple UI using clojurescript

### ISSUE THREAD

**Issue by unbalancedparentheses** [lambdaclass/holiday_pinger#13]

**Comment by facundoolano** [comment]
using a framework (like one of the react wrappers) for this seems overkill, but calling the js functions directly would also be weird (a lot of object mutation). A thin wrapper around the js DOM functions may work, check:

https://github.com/plumatic/dommy
https://github.com/jeluard/hipo/
https://github.com/levand/domina

Also ask on the clojure slack.

**Comment by facundoolano** [comment]
Intro to react: https://facebook.github.io/react/tutorial/tutorial.html#getting-started ✅ 

Om/O.next:
https://github.com/omcljs/om/wiki/Conceptual-overview ✅ 
https://github.com/omcljs/om/wiki/Basic-Tutorial ✅ 
~~https://github.com/omcljs/om/wiki/Quick-Start-(om.next)~~

Reagent/Re-frame
http://reagent-project.github.io/ ✅ 
https://github.com/Day8/re-frame/wiki/Creating-Reagent-Components ✅ 
https://github.com/Day8/re-frame/blob/master/README.md ✅ 
https://github.com/Day8/re-frame/blob/master/docs/ApplicationState.md ✅
https://github.com/Day8/re-frame/blob/master/docs/CodeWalkthrough.md ✅
https://github.com/Day8/re-frame/tree/master/examples/todomvc ✅
https://github.com/Day8/re-frame/blob/master/docs/Basic-App-Structure.md ✅
https://github.com/Day8/re-frame/blob/master/docs/EffectfulHandlers.md ✅
https://github.com/Day8/re-frame/blob/master/docs/Talking-To-Servers.md ✅

https://github.com/Day8/re-frame/blob/master/docs/Effects.md
https://github.com/Day8/re-frame/blob/master/docs/Coeffects.md
https://github.com/Day8/re-frame/blob/master/docs/Interceptors.md

https://purelyfunctional.tv/guide/reagent/
https://purelyfunctional.tv/guide/re-frame-building-blocks/

**Comment by facundoolano** [comment]
closing this as development of the ui is being done here https://github.com/lambdaclass/holiday_ping_ui
